### ISSUE TITLE
Use of sort in the code

### ISSUE THREAD

**Issue by vatsal13** [NSkelsey/algorithms#1]
```
def select(A, i): # A is a list, i is the ith element in that ordered list
                  # NOTE all elements must be unique
    T = list(A); T.sort()
```

Why are you using T.sort() -> this would initially sort the list . Then the final running time will not be O(n).

**Comment by NSkelsey** [comment]
Great catch, thanks.

I am surprised anybody is actually reading this code. 

I removed it and the algorithm actually works.

**Comment by vatsal13** [comment]
Yes, now it works.
